################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lib/opencv-4.1.0/modules/core/src/algorithm.cpp \
../lib/opencv-4.1.0/modules/core/src/alloc.cpp \
../lib/opencv-4.1.0/modules/core/src/arithm.cpp \
../lib/opencv-4.1.0/modules/core/src/arithm.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/array.cpp \
../lib/opencv-4.1.0/modules/core/src/batch_distance.cpp \
../lib/opencv-4.1.0/modules/core/src/bindings_utils.cpp \
../lib/opencv-4.1.0/modules/core/src/channels.cpp \
../lib/opencv-4.1.0/modules/core/src/check.cpp \
../lib/opencv-4.1.0/modules/core/src/command_line_parser.cpp \
../lib/opencv-4.1.0/modules/core/src/conjugate_gradient.cpp \
../lib/opencv-4.1.0/modules/core/src/convert.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/convert_c.cpp \
../lib/opencv-4.1.0/modules/core/src/convert_scale.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/copy.cpp \
../lib/opencv-4.1.0/modules/core/src/count_non_zero.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/cuda_gpu_mat.cpp \
../lib/opencv-4.1.0/modules/core/src/cuda_host_mem.cpp \
../lib/opencv-4.1.0/modules/core/src/cuda_info.cpp \
../lib/opencv-4.1.0/modules/core/src/cuda_stream.cpp \
../lib/opencv-4.1.0/modules/core/src/datastructs.cpp \
../lib/opencv-4.1.0/modules/core/src/directx.cpp \
../lib/opencv-4.1.0/modules/core/src/downhill_simplex.cpp \
../lib/opencv-4.1.0/modules/core/src/dxt.cpp \
../lib/opencv-4.1.0/modules/core/src/gl_core_3_1.cpp \
../lib/opencv-4.1.0/modules/core/src/glob.cpp \
../lib/opencv-4.1.0/modules/core/src/hal_internal.cpp \
../lib/opencv-4.1.0/modules/core/src/kmeans.cpp \
../lib/opencv-4.1.0/modules/core/src/lapack.cpp \
../lib/opencv-4.1.0/modules/core/src/lda.cpp \
../lib/opencv-4.1.0/modules/core/src/logger.cpp \
../lib/opencv-4.1.0/modules/core/src/lpsolver.cpp \
../lib/opencv-4.1.0/modules/core/src/lut.cpp \
../lib/opencv-4.1.0/modules/core/src/mathfuncs.cpp \
../lib/opencv-4.1.0/modules/core/src/mathfuncs_core.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/matmul.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_c.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_decomp.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_expressions.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_iterator.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_operations.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_sparse.cpp \
../lib/opencv-4.1.0/modules/core/src/matrix_wrap.cpp \
../lib/opencv-4.1.0/modules/core/src/mean.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/merge.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/minmax.cpp \
../lib/opencv-4.1.0/modules/core/src/norm.cpp \
../lib/opencv-4.1.0/modules/core/src/ocl.cpp \
../lib/opencv-4.1.0/modules/core/src/opengl.cpp \
../lib/opencv-4.1.0/modules/core/src/out.cpp \
../lib/opencv-4.1.0/modules/core/src/ovx.cpp \
../lib/opencv-4.1.0/modules/core/src/parallel.cpp \
../lib/opencv-4.1.0/modules/core/src/parallel_impl.cpp \
../lib/opencv-4.1.0/modules/core/src/pca.cpp \
../lib/opencv-4.1.0/modules/core/src/persistence.cpp \
../lib/opencv-4.1.0/modules/core/src/persistence_json.cpp \
../lib/opencv-4.1.0/modules/core/src/persistence_types.cpp \
../lib/opencv-4.1.0/modules/core/src/persistence_xml.cpp \
../lib/opencv-4.1.0/modules/core/src/persistence_yml.cpp \
../lib/opencv-4.1.0/modules/core/src/rand.cpp \
../lib/opencv-4.1.0/modules/core/src/softfloat.cpp \
../lib/opencv-4.1.0/modules/core/src/split.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/stat.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/stat_c.cpp \
../lib/opencv-4.1.0/modules/core/src/stl.cpp \
../lib/opencv-4.1.0/modules/core/src/sum.dispatch.cpp \
../lib/opencv-4.1.0/modules/core/src/system.cpp \
../lib/opencv-4.1.0/modules/core/src/tables.cpp \
../lib/opencv-4.1.0/modules/core/src/trace.cpp \
../lib/opencv-4.1.0/modules/core/src/types.cpp \
../lib/opencv-4.1.0/modules/core/src/umatrix.cpp \
../lib/opencv-4.1.0/modules/core/src/va_intel.cpp 

OBJS += \
./lib/opencv-4.1.0/modules/core/src/algorithm.o \
./lib/opencv-4.1.0/modules/core/src/alloc.o \
./lib/opencv-4.1.0/modules/core/src/arithm.o \
./lib/opencv-4.1.0/modules/core/src/arithm.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/array.o \
./lib/opencv-4.1.0/modules/core/src/batch_distance.o \
./lib/opencv-4.1.0/modules/core/src/bindings_utils.o \
./lib/opencv-4.1.0/modules/core/src/channels.o \
./lib/opencv-4.1.0/modules/core/src/check.o \
./lib/opencv-4.1.0/modules/core/src/command_line_parser.o \
./lib/opencv-4.1.0/modules/core/src/conjugate_gradient.o \
./lib/opencv-4.1.0/modules/core/src/convert.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/convert_c.o \
./lib/opencv-4.1.0/modules/core/src/convert_scale.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/copy.o \
./lib/opencv-4.1.0/modules/core/src/count_non_zero.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/cuda_gpu_mat.o \
./lib/opencv-4.1.0/modules/core/src/cuda_host_mem.o \
./lib/opencv-4.1.0/modules/core/src/cuda_info.o \
./lib/opencv-4.1.0/modules/core/src/cuda_stream.o \
./lib/opencv-4.1.0/modules/core/src/datastructs.o \
./lib/opencv-4.1.0/modules/core/src/directx.o \
./lib/opencv-4.1.0/modules/core/src/downhill_simplex.o \
./lib/opencv-4.1.0/modules/core/src/dxt.o \
./lib/opencv-4.1.0/modules/core/src/gl_core_3_1.o \
./lib/opencv-4.1.0/modules/core/src/glob.o \
./lib/opencv-4.1.0/modules/core/src/hal_internal.o \
./lib/opencv-4.1.0/modules/core/src/kmeans.o \
./lib/opencv-4.1.0/modules/core/src/lapack.o \
./lib/opencv-4.1.0/modules/core/src/lda.o \
./lib/opencv-4.1.0/modules/core/src/logger.o \
./lib/opencv-4.1.0/modules/core/src/lpsolver.o \
./lib/opencv-4.1.0/modules/core/src/lut.o \
./lib/opencv-4.1.0/modules/core/src/mathfuncs.o \
./lib/opencv-4.1.0/modules/core/src/mathfuncs_core.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/matmul.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/matrix.o \
./lib/opencv-4.1.0/modules/core/src/matrix_c.o \
./lib/opencv-4.1.0/modules/core/src/matrix_decomp.o \
./lib/opencv-4.1.0/modules/core/src/matrix_expressions.o \
./lib/opencv-4.1.0/modules/core/src/matrix_iterator.o \
./lib/opencv-4.1.0/modules/core/src/matrix_operations.o \
./lib/opencv-4.1.0/modules/core/src/matrix_sparse.o \
./lib/opencv-4.1.0/modules/core/src/matrix_wrap.o \
./lib/opencv-4.1.0/modules/core/src/mean.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/merge.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/minmax.o \
./lib/opencv-4.1.0/modules/core/src/norm.o \
./lib/opencv-4.1.0/modules/core/src/ocl.o \
./lib/opencv-4.1.0/modules/core/src/opengl.o \
./lib/opencv-4.1.0/modules/core/src/out.o \
./lib/opencv-4.1.0/modules/core/src/ovx.o \
./lib/opencv-4.1.0/modules/core/src/parallel.o \
./lib/opencv-4.1.0/modules/core/src/parallel_impl.o \
./lib/opencv-4.1.0/modules/core/src/pca.o \
./lib/opencv-4.1.0/modules/core/src/persistence.o \
./lib/opencv-4.1.0/modules/core/src/persistence_json.o \
./lib/opencv-4.1.0/modules/core/src/persistence_types.o \
./lib/opencv-4.1.0/modules/core/src/persistence_xml.o \
./lib/opencv-4.1.0/modules/core/src/persistence_yml.o \
./lib/opencv-4.1.0/modules/core/src/rand.o \
./lib/opencv-4.1.0/modules/core/src/softfloat.o \
./lib/opencv-4.1.0/modules/core/src/split.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/stat.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/stat_c.o \
./lib/opencv-4.1.0/modules/core/src/stl.o \
./lib/opencv-4.1.0/modules/core/src/sum.dispatch.o \
./lib/opencv-4.1.0/modules/core/src/system.o \
./lib/opencv-4.1.0/modules/core/src/tables.o \
./lib/opencv-4.1.0/modules/core/src/trace.o \
./lib/opencv-4.1.0/modules/core/src/types.o \
./lib/opencv-4.1.0/modules/core/src/umatrix.o \
./lib/opencv-4.1.0/modules/core/src/va_intel.o 

CPP_DEPS += \
./lib/opencv-4.1.0/modules/core/src/algorithm.d \
./lib/opencv-4.1.0/modules/core/src/alloc.d \
./lib/opencv-4.1.0/modules/core/src/arithm.d \
./lib/opencv-4.1.0/modules/core/src/arithm.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/array.d \
./lib/opencv-4.1.0/modules/core/src/batch_distance.d \
./lib/opencv-4.1.0/modules/core/src/bindings_utils.d \
./lib/opencv-4.1.0/modules/core/src/channels.d \
./lib/opencv-4.1.0/modules/core/src/check.d \
./lib/opencv-4.1.0/modules/core/src/command_line_parser.d \
./lib/opencv-4.1.0/modules/core/src/conjugate_gradient.d \
./lib/opencv-4.1.0/modules/core/src/convert.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/convert_c.d \
./lib/opencv-4.1.0/modules/core/src/convert_scale.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/copy.d \
./lib/opencv-4.1.0/modules/core/src/count_non_zero.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/cuda_gpu_mat.d \
./lib/opencv-4.1.0/modules/core/src/cuda_host_mem.d \
./lib/opencv-4.1.0/modules/core/src/cuda_info.d \
./lib/opencv-4.1.0/modules/core/src/cuda_stream.d \
./lib/opencv-4.1.0/modules/core/src/datastructs.d \
./lib/opencv-4.1.0/modules/core/src/directx.d \
./lib/opencv-4.1.0/modules/core/src/downhill_simplex.d \
./lib/opencv-4.1.0/modules/core/src/dxt.d \
./lib/opencv-4.1.0/modules/core/src/gl_core_3_1.d \
./lib/opencv-4.1.0/modules/core/src/glob.d \
./lib/opencv-4.1.0/modules/core/src/hal_internal.d \
./lib/opencv-4.1.0/modules/core/src/kmeans.d \
./lib/opencv-4.1.0/modules/core/src/lapack.d \
./lib/opencv-4.1.0/modules/core/src/lda.d \
./lib/opencv-4.1.0/modules/core/src/logger.d \
./lib/opencv-4.1.0/modules/core/src/lpsolver.d \
./lib/opencv-4.1.0/modules/core/src/lut.d \
./lib/opencv-4.1.0/modules/core/src/mathfuncs.d \
./lib/opencv-4.1.0/modules/core/src/mathfuncs_core.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/matmul.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/matrix.d \
./lib/opencv-4.1.0/modules/core/src/matrix_c.d \
./lib/opencv-4.1.0/modules/core/src/matrix_decomp.d \
./lib/opencv-4.1.0/modules/core/src/matrix_expressions.d \
./lib/opencv-4.1.0/modules/core/src/matrix_iterator.d \
./lib/opencv-4.1.0/modules/core/src/matrix_operations.d \
./lib/opencv-4.1.0/modules/core/src/matrix_sparse.d \
./lib/opencv-4.1.0/modules/core/src/matrix_wrap.d \
./lib/opencv-4.1.0/modules/core/src/mean.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/merge.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/minmax.d \
./lib/opencv-4.1.0/modules/core/src/norm.d \
./lib/opencv-4.1.0/modules/core/src/ocl.d \
./lib/opencv-4.1.0/modules/core/src/opengl.d \
./lib/opencv-4.1.0/modules/core/src/out.d \
./lib/opencv-4.1.0/modules/core/src/ovx.d \
./lib/opencv-4.1.0/modules/core/src/parallel.d \
./lib/opencv-4.1.0/modules/core/src/parallel_impl.d \
./lib/opencv-4.1.0/modules/core/src/pca.d \
./lib/opencv-4.1.0/modules/core/src/persistence.d \
./lib/opencv-4.1.0/modules/core/src/persistence_json.d \
./lib/opencv-4.1.0/modules/core/src/persistence_types.d \
./lib/opencv-4.1.0/modules/core/src/persistence_xml.d \
./lib/opencv-4.1.0/modules/core/src/persistence_yml.d \
./lib/opencv-4.1.0/modules/core/src/rand.d \
./lib/opencv-4.1.0/modules/core/src/softfloat.d \
./lib/opencv-4.1.0/modules/core/src/split.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/stat.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/stat_c.d \
./lib/opencv-4.1.0/modules/core/src/stl.d \
./lib/opencv-4.1.0/modules/core/src/sum.dispatch.d \
./lib/opencv-4.1.0/modules/core/src/system.d \
./lib/opencv-4.1.0/modules/core/src/tables.d \
./lib/opencv-4.1.0/modules/core/src/trace.d \
./lib/opencv-4.1.0/modules/core/src/types.d \
./lib/opencv-4.1.0/modules/core/src/umatrix.d \
./lib/opencv-4.1.0/modules/core/src/va_intel.d 


# Each subdirectory must supply rules for building sources it contributes
lib/opencv-4.1.0/modules/core/src/%.o: ../lib/opencv-4.1.0/modules/core/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -DOMPI_SKIP_MPICXX -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -I/usr/include/mpi -I/home/vayalala/workspace2/OpenCLExercise3_Sobel/lib -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


